{ lib, outputs, ... }: {
  variable.LINODE_TOKEN = {
    type = "string";
    description = "Linode API token";
    nullable = false;
    sensitive = true;
  };

  terraform.required_providers.linode.source = "linode/linode";

  provider.linode.token = "\${ var.LINODE_TOKEN }";

  resource.linode_image.nixos =
  let
    img_dir = outputs.packages.x86_64-linux.linode;
    img = builtins.elemAt (lib.mapAttrsToList (name: _: img_dir + "/${name}") (builtins.readDir img_dir)) 0;
  in {
    label = "nixos-test-image";
    description = "Image generated by nixos-generator";
    region = "us-southeast";

    # Hash also acheived by using nix store, since hash is in path :P
    file_path = img;
  };

  resource.linode_instance.nixos-test = {
    label = "nixos-test";
    group = "nixos";
    tags = [ "nixos" "test-instances" ];
    region = "us-southeast";
    type = "g6-nanode-1";
    root_pass = "Thisisabadpassword123!!!";

    image = "\${linode_image.nixos.id}";
  };
}
